### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by cichy** [nemanjam/eshop-page#1]
A cross-origin error was thrown

**Comment by nemanjam** [comment]
I'm successfully logged in with Google if that's what you mean.

![Screenshot_1](https://user-images.githubusercontent.com/9990165/65874689-6fa94d80-e386-11e9-90ee-73ac52f7d38d.png)

**Comment by nemanjam** [comment]
@cichy I updated the repo, can you try again?

**Comment by cichy** [comment]
working fine you can close an issue, peace
